import logging
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

_TEMPLATE = """\
# Claude Code Instructions
> Auto-generated by Plaude Code
> Source: {source_filename}
> Generated: {timestamp}
> Project: {project_dir}

---

## Task

The following is a voice transcript describing work to be done in this directory.
Read it carefully. Infer what needs to be built, fixed, or continued.
Execute it completely. Do not stop halfway.

**Rules:**
- Work entirely within this directory
- Find existing files before assuming they don't exist
- Make reasonable implementation decisions where the transcript is ambiguous
- After completing all tasks, write a brief DONE.md summarising every change made

---

## Transcript

{transcript_text}

---
*End of auto-generated instructions.*
"""


def write_claude_md(
    transcript_text: str, source_filename: str, project_dir: Path
) -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    content = _TEMPLATE.format(
        source_filename=source_filename,
        timestamp=timestamp,
        project_dir=project_dir,
        transcript_text=transcript_text,
    )
    out = project_dir / "CLAUDE.md"
    out.write_text(content, encoding="utf-8")
    logger.info(f"✓ CLAUDE.md written to {out}")
    return out


def launch_claude(project_dir: Path, claude_cmd: str = "claude") -> None:
    if not shutil.which(claude_cmd):
        raise RuntimeError(
            f"'{claude_cmd}' not found on PATH. Install Claude Code CLI first."
        )
    subprocess.Popen([claude_cmd], cwd=str(project_dir))
    logger.info(f"✓ Claude Code launched in {project_dir}")


def write_fallback_md(transcript_text: str, source_filename: str) -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_dir = Path.home() / "Desktop" / "plaude-unmatched" / timestamp
    out_dir.mkdir(parents=True, exist_ok=True)

    warning = (
        "⚠️ Project directory not detected. "
        "Move this file to the correct project and run `claude` manually.\n\n"
    )
    content = warning + _TEMPLATE.format(
        source_filename=source_filename,
        timestamp=timestamp,
        project_dir="(unknown)",
        transcript_text=transcript_text,
    )
    out = out_dir / "CLAUDE.md"
    out.write_text(content, encoding="utf-8")
    logger.info(f"✓ Fallback CLAUDE.md written to {out}")
    return out
